name: Main branch workflow

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

permissions:
  contents: write
  packages: write

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  validation:
    name: Run validation & release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://npm.pkg.github.com"

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Configure git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "github-action@users.noreply.github.com"

      - name: Remove old .npmrc
        run: rm -f .npmrc

      - name: Set up .npmrc in project root for GitHub Packages
        run: |
          echo "@gracenote-team:registry=https://npm.pkg.github.com/" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=${NPM_TOKEN}" >> .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run release
